{% set version = "1.6.0" %}

package:
  name: g2clib
  version: {{ version }}

source:
  url: http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/g2clib-{{ version }}.tar
  sha256: afec1ea29979b84369d0f46f305ed12f73f1450ec2db737664ec7f75c1163add

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - libpng >=1.6.32,<1.6.35
    - zlib 1.2.11
    - jasper
  run:
    - libpng >=1.6.32,<1.6.35
    - zlib 1.2.11
    - jasper

test:
  commands:
    - test -f ${PREFIX}/lib/libgrib2c.a  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/
  license: Public Domain
  summary: 'C decoder/encoder routines for GRIB edition 2.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
